services:
  coasterpediaapi:
    image: ghcr.io/coasterpedia/coasterpedia-api/api@${API_IMAGE}
    restart: always
    networks:
      - web
    environment:
      ConnectionString: Server=${MYSQL_SERVER};database=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD};Charset=utf8;
    labels:
      - traefik.http.routers.coasterpediaapi.rule=Host(`api.coasterpedia.net`)
      - traefik.http.routers.coasterpediaapi.entrypoints=web,websecure
      - traefik.http.services.coasterpediaapi.loadbalancer.server.port=8080
networks:
  web:
    external: true