services:
  coasterpediaapi:
    image: ghcr.io/coasterpedia/coasterpedia-api/api@${API_IMAGE}
    restart: always
    networks:
      - coasterpedia_web
    environment:
      ConnectionStrings__DefaultConnection: Server=${MYSQL_SERVER};database=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD};Charset=utf8;
networks:
  coasterpedia_web:
    external: true